name: Production Deployment

on:
  push:
    branches: [prod]
  workflow_dispatch:

env:
  COMPOSE_FILE: docker-compose.prod.yml

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DB_ENV=${{ secrets.DB_ENV }}
          NEO4J_LOCAL_URI=${{ secrets.NEO4J_LOCAL_URI }}
          NEO4J_LOCAL_CONTAINER_URI=${{ secrets.NEO4J_LOCAL_CONTAINER_URI }}
          NEO4J_LOCAL_USERNAME=${{ secrets.NEO4J_LOCAL_USERNAME }}
          NEO4J_LOCAL_PASSWORD=${{ secrets.NEO4J_LOCAL_PASSWORD }}
          NEO4J_LOCAL_CONTAINER_PASSWORD=${{ secrets.NEO4J_LOCAL_CONTAINER_PASSWORD }}
          NEO4J_AURA_URI=${{ secrets.NEO4J_AURA_URI }}
          NEO4J_AURA_USERNAME=${{ secrets.NEO4J_AURA_USERNAME }}
          NEO4J_AURA_PASSWORD=${{ secrets.NEO4J_AURA_PASSWORD }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          AES_ENCRYPTION_KEY=${{ secrets.AES_ENCRYPTION_KEY }}
          SENDGUN_API_KEY=${{ secrets.SENDGUN_API_KEY }}
          GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
          SENDER_GMAIL=${{ secrets.SENDER_GMAIL }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          PORT=${{ secrets.PORT }}
          ENV=${{ secrets.ENV }}
          EOF
        shell: bash
        
      - name: Determine deployment color
        id: color
        run: |
          # Check which color is currently active
          if docker ps | grep -q "alumni-api-blue"; then
            echo "NEW_COLOR=green" >> $GITHUB_ENV
            echo "OLD_COLOR=blue" >> $GITHUB_ENV
          else
            echo "NEW_COLOR=blue" >> $GITHUB_ENV
            echo "OLD_COLOR=green" >> $GITHUB_ENV
          fi
          echo "Deploying to $NEW_COLOR"
          
      - name: Build new container
        run: docker-compose -f docker-compose.prod.yml --env-file .env build api-$NEW_COLOR
        
      - name: Start new container
        run: |
          docker-compose -f docker-compose.prod.yml --env-file .env up -d api-$NEW_COLOR
          
          # Wait for new container to be healthy
          timeout 120 bash -c 'while [[ "$(docker inspect -f "{{.State.Health.Status}}" alumni-api-$NEW_COLOR)" != "healthy" ]]; do sleep 5; done' || false
          
      - name: Switch traffic
        run: |
          # Make the new container active
          docker exec nginx /bin/sh /scripts/switch-color.sh
          
          # Verify switch
          CURRENT_COLOR=$(docker exec nginx grep -oP 'server alumni-api-\K(blue|green)' /etc/nginx/nginx.conf)
          if [ "$CURRENT_COLOR" != "$NEW_COLOR" ]; then
            echo "Color switch failed!"
            exit 1
          fi
          
      - name: Stop old container
        run: |
          docker-compose stop api-$OLD_COLOR
          
      - name: Clean up
        run: |
          docker system prune -f
